version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Lancement des tests unitaires..."
      - npm test
  build:
    commands:
      - echo "Si les tests passent, on build..."
      - minify index.html > index.min.html
artifacts:
  files:
    - index.html
