version: 0.2

phases:
  pre_build:
    commands:
      - echo "Connexion à Amazon ECR..."
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 176319219989.dkr.ecr.eu-west-1.amazonaws.com/mon-application-docker
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
  build:
    commands:
      - echo "Construction de l'image Docker..."
      - docker build -t 176319219989.dkr.ecr.eu-west-1.amazonaws.com/mon-application-docker:latest .
      - docker build -t 176319219989.dkr.ecr.eu-west-1.amazonaws.com/mon-application-docker:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Envoi de l'image sur ECR..."
      - docker push 176319219989.dkr.ecr.eu-west-1.amazonaws.com/mon-application-docker:latest
      - docker push 176319219989.dkr.ecr.eu-west-1.amazonaws.com/mon-application-docker:$IMAGE_TAG
      - echo "Génération du fichier d'artefact pour Elastic Beanstalk..."
      - printf '[{"name":"web","imageUri":"%s"}]' 176319219989.dkr.ecr.eu-west-1.amazonaws.com/mon-application-docker:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
